### ISSUE TITLE
Mutating properties in property sets and run-time properties

### ISSUE THREAD

**Issue by jwtowner** [facebookresearch/pushmi#52]
Is it intended to never be able to change a property if one with the same category already exists in the property_set? A use case I can think of is if you add a priority or quality-of-service category and a user needs to change the priority level for a sender that already has an existing priority to bound.

Specifically, I'm looking at the the overload of `__property_set_insert_fn` that handles insertion of a property when there is already one with a matching category. Currently, `PIn` (the input property to be inserted) can never end up in the output `property_set`. Changing it to the following would overwrite any property with a matching category:

```c++
template <class PIn, class PMatch, class... Ps>
property_set<std::conditional_t<PUSHMI_PP_IS_SAME(Ps, PMatch), PIn, Ps>...>
__property_set_insert_fn(property_set<Ps...>, property_set_element<PMatch, property_category_t<PIn>>);
```

Another question I have is properties with state that may only be known at run-time. Would these need to be handled through a different mechanism rather than the property system? Consider a thread-affinity and numa node property category, where the total number of processor cores or numa nodes won't be known until the program is run.

The property and customization point system in [P0443](https://wg21.link/p0443) sort of provides some of the requisite machinery to allow for run-time properties, where you can potentially provide non-constexpr `require`, `prefer` and `query` extensions and/or pass in non-constexpr property objects.

However, in the reference implementations I've looked at none of the polymorphic adapters ever bother to store runtime state as data members. I think what would be be needed would be to generate a `std::tuple` of the `polymorphic_query_result_type`s of the properties while filtering out properties with values that are known at compile-time so that it only contains the ones with run-time values. Then propagate this state on subsequent `require` and `prefer` invocations, or pull values from the tuple for matching `query` calls.

But I don't see how this would be possible with the strictly compile-time property system in pushmi. Are there any plans to support this, if not in pushmi, than in what comes out of the synthesis of [P0443](https://wg21.link/p0443), [P1054](https://wg21.link/p1054) and [P1055](https://wg21.link/p1055)?

**Comment by kirkshoop** [comment]
# Compile Time

Yes, it is intended that properties can be changed at compile time. I just updated the facade classes that take a Data to use `property_set_insert_t` to merge in properties from Data.

These properties do not intend to support 'rebinding' ala allocators. Having used allocators, that is a pattern that I try to avoid.

@ericniebler wrote that implementation of `property_set_insert_t`. I have observed that it works as intended. The intent is to apply each property in PS1 (the right-hand-side) to PS0 (the left-hand-side)

```cpp
template <class PS0, class PS1>
using property_set_insert_t =
  typename std::enable_if_t<
    PropertySet<PS0> && PropertySet<PS1>,
    detail::property_set_insert<PS0, PS1>>::type;
```

So POut is the new property that is expected to replace PIn

```cpp
template <class PIn, class POut, class...Ps>
property_set<std::conditional_t<PUSHMI_PP_IS_SAME(Ps, PIn), POut, Ps>...>
__property_set_insert_fn(property_set<Ps...>, property_set_element<POut, property_category_t<PIn>>);
```

# Runtime

pushmi follows a similar model to what @chriskohlhoff just added in the [interface-properties branch](https://github.com/executors/executors-impl/tree/interface-properties). Each interface changing concept has an independent set of functions and a matching polymorphic type. 

In Pushmi this can be seen in the time_single_sender where the runtime property now() is added.

# Synthesis

@LeeHowes, @brycelelbach and @dhollman are working on a proposal now that uses the existing [p0443](https://wg21.link/p0443) properties system. 

@ericniebler is also working on a branch based on the [interface-properties branch](https://github.com/executors/executors-impl/tree/interface-properties) by @chriskohlhoff that implements the proposal.

Even though it is not needed to express the compile time or runtime properties in pushmi, pushmi could switch to the [p0443](https://wg21.link/p0443) properties system if desired.

**Comment by jwtowner** [comment]
Thanks for the information. I see now how you can add and store arbitrary properties in the lifted/adapted receivers & senders, and how only the final expression needs to be type-erased when passed to an executor or across some other boundary. Rather ingenious. A problem I've encountered with the polymorphic interface adapters from the interface-properties branch is that the virtual require/prefer member functions have a tendency to recursively instantiate a lot of template classes and generate a lot of code to handle every possible combination of conformed interface property. I might be mistaken, but the pushmi model doesn't seem to suffer from this.

**Comment by jwtowner** [comment]
Closing this, thanks again.
